on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.10.5'

    - name: Unzip Flutter project
      run: unzip xtreme_text_styler.zip

    - name: Get dependencies
      run: flutter pub get

    - name: Build APK
      run: flutter build apk

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: xtreme-apk
        path: build/app/outputs/flutter-apk/app-release.apk
        
